---
title: "Build DIO Model"
output:
  md_document:
    variant: gfm
params:
    modelname: "DIOv2.0"
---


```{r setup, include=FALSE}

## Install useeior version with hybridization

#First check that devtools package is installed
if (!"devtools"%in%installed.packages()[, "Package"]) {
    install.packages("devtools")
}
library(devtools)

#devtools::install_github("USEPA/useeior@v1.1.0")
# devtools::load_all("../useeior")

## Build the model using useeior
library(useeior)
library(logging)
# Identify the model specifications file for the selected DIO model
modelspec <- paste0(params$modelname, ".yml")
hybridspec <- "DIOProcesses.yml"
configpaths <- file.path("data", c(modelspec,hybridspec))

log_file <- "model/build_and_save_DIO_model.log"
if (file.exists(log_file)){
  file.remove(log_file)
}
addHandler(writeToFile, file=log_file)

DIO <- useeior::buildModel(params$modelname, configpaths)
useeior::writeModeltoXLSX(DIO, 'model')
loginfo("Saving model to model/DIO.rds")
saveRDS(DIO, "model/DIO.rds") 

# model <- initializeModel(params$modelname, configpaths)
# model <- loadIOData(model, configpaths)
# model <- loadandbuildSatelliteTables(model)
# model <- loadandbuildIndicators(model)
# model <- loadDemandVectors(model)
# model <- constructEEIOMatrices(model)




```

## Validate Model

Validate that commodity output can be recalculated (within 1%) with the model total requirements matrix (L) and demand vector (y) for US production
```{r}
econval <- compareOutputandLeontiefXDemand(DIO, tolerance = 0.01)
print(paste("Number of sectors passing:",econval$N_Pass))
print(paste("Number of sectors failing:",econval$N_Fail))
print(paste("Sectors failing:", paste(econval$Failure$rownames, collapse = ", ")))
```



Write the model to Excel
```{r setup, include=FALSE}

useeior::writeModeltoXLSX(DIO,"../DIOv2.xlsx")
```